networks:
  application-tests:

services:
  #  api:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: api
  #    environment:
  #      - "DatabaseSettings__ConnectionString=Server=db;Database=root-db;User=root;Password=DeV12345;MultipleActiveResultSets=true"
  #      - "DatabaseSettings__DBProvider=mysql"
  #      - "HangfireSettings__Storage__ConnectionString=Server=db;Database=root-db;User=root;Password=DeV12345;MultipleActiveResultSets=true;Allow User Variables=true"
  #      - "HangfireSettings__Storage__StorageProvider=mysql"
  #      - "ASPNETCORE_Kestrel__Certificates__Default__Password=DeV12345"
  #      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/DN.Host.pfx"
  #    volumes:
  #      - ~/.aspnet/https:/https:ro
  #    ports:
  #      - "5050:5050"
  #      - "5060:5060"
  #    depends_on:
  #      - db
  #    restart: on-failure
  mysql-db:
    networks:
      - application-tests
    ports:
      - "3306:3306"
    image: "amd64/mysql:8.0-oracle"
#    image: "arm64v8/mysql:oracle"
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "DeV12345"
      MYSQL_PASSWORD: "DeV12345"
#      MYSQL_USER: "root"
#      MYSQL_DATABASE: "root-db"
