version: '3.8'

services:
  postgres-db:
    image: "postgres:13"
    container_name: postgres-db
    environment:
      - POSTGRES_USER=psqluser
      - POSTGRES_PASSWORD=DeV12345
      - POSTGRES_DB=root_tenant_db
    ports:
      - "5432:5432"
    restart: always

  seq-log:
    image: datalust/seq:latest
    container_name: seq-log
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:5341"
      - "5342:80"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:DBProvider=postgresql
      - DatabaseSettings:ConnectionString=Server=postgres-db;Database=root_tenant_db;Uid=psqluser;Pwd=DeV12345
      - DatabaseSettings:ConnectionStringTemplate=postgres-db;Port=5432;Database={0};Uid=psqluser;Pwd=DeV12345
      - HangfireSettings:Storage:StorageProvider=postgresql
      - HangfireSettings:Storage:ConnectionString=Server=postgres-db;Database=root_tenant_db;Uid=psqluser;Pwd=DeV12345
      - Serilog:WriteTo:0:Name=Seq
      - Serilog:WriteTo:0:Args:serverUrl=http://seq-log:5341
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
      - seq-log
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=DeV12345
      - PGADMIN_SETUP_HOST=postgres-db
    ports:
      - "8089:80"
    depends_on:
      - postgres-db
    restart: always
