using MediatR;
using System;
using System.ComponentModel.DataAnnotations;

namespace FSH.WebApi.Application.Accounting.CreditMemos;

public class CreateCreditMemoRequest : IRequest<Guid>
{
    [Required]
    public Guid CustomerId { get; set; }

    [Required]
    public DateTime Date { get; set; }

    [Required]
    [MaxLength(500)]
    public string Reason { get; set; } = default!;

    [Required]
    [Range(0.01, double.MaxValue, ErrorMessage = "Total Amount must be greater than zero.")]
    public decimal TotalAmount { get; set; }

    [Required]
    [MaxLength(3)] // E.g., "USD", "EUR"
    public string Currency { get; set; } = "USD"; // Default currency

    [MaxLength(2000)]
    public string? Notes { get; set; }

    public Guid? OriginalCustomerInvoiceId { get; set; } // Optional

    // CreditMemoNumber will be auto-generated by the handler.
    // Status will be set by the handler, typically to Draft or Approved.
}
